In [7]:
import numpy as np

In [8]:
from sklearn.datasets import load_iris

In [9]:
iris = load_iris()

In [10]:
type(iris)

sklearn.utils.Bunch

In [12]:
X = iris.data

In [13]:
y = iris.target

In [15]:
from keras.utils import to_categorical

In [16]:
y = to_categorical(y)

In [18]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler_object = MinMaxScaler()

In [27]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [30]:
scaled_X_train = scaler_object.transform(X_train)

In [47]:
scaled_X_test = scaler_object.transform(X_test)

In [34]:
from keras.models import Sequential
from keras.layers import Dense

In [39]:
model = Sequential()

In [40]:
model.add(Dense(units=8, activation='relu', input_dim=4))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [41]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [42]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Instructions for updating:
Use tf.cast instead.
Epoch 1/150
 - 1s - loss: 1.0668 - acc: 0.4381
Epoch 2/150
 - 0s - loss: 1.0560 - acc: 0.3048
Epoch 3/150
 - 0s - loss: 1.0451 - acc: 0.3905
Epoch 4/150
 - 0s - loss: 1.0344 - acc: 0.4000
Epoch 5/150
 - 0s - loss: 1.0243 - acc: 0.4476
Epoch 6/150
 - 0s - loss: 1.0148 - acc: 0.4952
Epoch 7/150
 - 0s - loss: 1.0056 - acc: 0.5048
Epoch 8/150
 - 0s - loss: 0.9967 - acc: 0.5143
Epoch 9/150
 - 0s - loss: 0.9877 - acc: 0.5238
Epoch 10/150
 - 0s - loss: 0.9790 - acc: 0.5524
Epoch 11/150
 - 0s - loss: 0.9704 - acc: 0.6190
Epoch 12/150
 - 0s - loss: 0.9625 - acc: 0.6286
Epoch 13/150
 - 0s - loss: 0.9546 - acc: 0.6286
Epoch 14/150
 - 0s - loss: 0.9462 - acc: 0.6286
Epoch 15/150
 - 0s - loss: 0.9383 - acc: 0.6286
Epoch 16/150
 - 0s - loss: 0.9300 - acc: 0.6286
Epoch 17/150
 - 0s - loss: 0.9215 - acc: 0.6286
Epoch 18/150
 - 0s - loss: 0.9134 - acc: 0.6286
Epoch 19/150
 - 0s - loss: 0.9050 - acc: 0.6286
Epoch 20/150
 - 0s - loss: 0.8967 - acc: 0.6381
E

In [48]:
predictions = model.predict_classes(scaled_X_test)

In [49]:
predictions

array([2, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [50]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [53]:
y_test_arg = y_test.argmax(axis=1)

In [52]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [54]:
print(confusion_matrix(y_test_arg, predictions))

[[19  0  0]
 [ 0 10  3]
 [ 0  0 13]]


In [55]:
print(classification_report(y_test_arg, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.77      0.87        13
           2       0.81      1.00      0.90        13

   micro avg       0.93      0.93      0.93        45
   macro avg       0.94      0.92      0.92        45
weighted avg       0.95      0.93      0.93        45



In [56]:
print(accuracy_score(y_test_arg, predictions))

0.9333333333333333


In [57]:
model.save('myfirstmodel.h5')

In [58]:
from keras.models import load_model

In [59]:
new_model = load_model('myfirstmodel.h5')

In [60]:
new_model.predict_classes(scaled_X_test)

array([2, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])